name: Windows
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 
  workflow_dispatch:
  # push代码时触发workflow
  #push:
  #  branches:
  #    - dev
  #    - master

  #pull_request:
  #  branches:
  #    - dev
  #    - master
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 5.15.2 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_5152/
          - qt_ver: 5.15.2          
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_target: x64
            qt_arch_install: msvc2019_64    
            python-version: '3.10'     
    env:
      targetName: Capture2Text.exe
    # 步骤
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # 安装Qt
      - name: Install Qt
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v4
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cache: 'false'
      # 拉取代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up prequisition
        shell: cmd
        run: |
          pip install --force-reinstall -v "conan==1.64.1"
          conan install . --build=missing

      - name: msvc-build Capture2Text
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          qmake 
          nmake
          nmake clean
          qmake CONFIG+=console
          nmake

          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"    
          echo "::set-output name=release_date::$(date +'%Y%m%d')"    
          echo "::set-output name=release_time::$(date +'%H%M%S')"    
          echo "::set-output name=release_time_clock::$(date +'%H:%M:%S')"    
      # 打包 
      - name: package
        id: package      
        env:
          archiveName: Capture2Text-${{ github.ref_name }}.${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.release_time }}
          msvcArch: ${{ matrix.msvc_arch }}
        shell: pwsh
        run: |
          & .github\scripts\windows-publish.ps1 ${env:archiveName} ${env:targetName}
           $name = ${env:archiveName}
           echo "::set-output name=packageName::$name" 

      - name: uploadRelease
        # if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.packageName }}.zip
          asset_name: ${{ steps.package.outputs.packageName }}.zip
          tag: prerelease-${{steps.vars.outputs.release_date}}
          overwrite: true 
          release_name: Windows-${{ github.ref_name }}.${{ steps.vars.outputs.sha_short }} built on ${{steps.vars.outputs.release_date}}  ${{steps.vars.outputs.release_time_clock}}  
          prerelease: true
          body: |
            Release on date: ${{steps.vars.outputs.release_date}} Time: ${{steps.vars.outputs.release_time_clock}}  
            Branch:          ${{ github.ref_name }}
            Commit:          ${{ steps.vars.outputs.sha_short }} 
            Qt version:      ${{ matrix.qt_ver }} ${{ matrix.qt_arch }}
            Built with:      MSVC-64 Visual studio 2019

